//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 03:05:54 PM PKT 
//


package com.hourtimesheet.desktop;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hourtimesheet.desktop package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PONumber_QNAME = new QName("", "PONumber");
    private final static QName _AgencyLogin_QNAME = new QName("", "AgencyLogin");
    private final static QName _CompanyID_QNAME = new QName("", "CompanyID");
    private final static QName _FromModifiedDate_QNAME = new QName("", "FromModifiedDate");
    private final static QName _DateMacro_QNAME = new QName("", "DateMacro");
    private final static QName _MatchCriterion_QNAME = new QName("", "MatchCriterion");
    private final static QName _CreditAmount_QNAME = new QName("", "CreditAmount");
    private final static QName _Gender_QNAME = new QName("", "Gender");
    private final static QName _PaymentAmount_QNAME = new QName("", "PaymentAmount");
    private final static QName _DetailAccountType_QNAME = new QName("", "DetailAccountType");
    private final static QName _MaxReturned_QNAME = new QName("", "MaxReturned");
    private final static QName _ActiveStatus_QNAME = new QName("", "ActiveStatus");
    private final static QName _ReorderPoint_QNAME = new QName("", "ReorderPoint");
    private final static QName _AppID_QNAME = new QName("", "AppID");
    private final static QName _ClientDateTime_QNAME = new QName("", "ClientDateTime");
    private final static QName _IncludeLineItems_QNAME = new QName("", "IncludeLineItems");
    private final static QName _DayOfMonthDue_QNAME = new QName("", "DayOfMonthDue");
    private final static QName _OpenAmount_QNAME = new QName("", "OpenAmount");
    private final static QName _NameOnCheck_QNAME = new QName("", "NameOnCheck");
    private final static QName _InstallationID_QNAME = new QName("", "InstallationID");
    private final static QName _TargetLogin_QNAME = new QName("", "TargetLogin");
    private final static QName _TxnType_QNAME = new QName("", "TxnType");
    private final static QName _DueNextMonthDays_QNAME = new QName("", "DueNextMonthDays");
    private final static QName _Rate_QNAME = new QName("", "Rate");
    private final static QName _JobProjectedEndDate_QNAME = new QName("", "JobProjectedEndDate");
    private final static QName _Subtotal_QNAME = new QName("", "Subtotal");
    private final static QName _CompanyType_QNAME = new QName("", "CompanyType");
    private final static QName _ShipDate_QNAME = new QName("", "ShipDate");
    private final static QName _AltContact_QNAME = new QName("", "AltContact");
    private final static QName _DiscountAmount_QNAME = new QName("", "DiscountAmount");
    private final static QName _TxnID_QNAME = new QName("", "TxnID");
    private final static QName _Suffix_QNAME = new QName("", "Suffix");
    private final static QName _JobStartDate_QNAME = new QName("", "JobStartDate");
    private final static QName _BillableStatus_QNAME = new QName("", "BillableStatus");
    private final static QName _MarkupRate_QNAME = new QName("", "MarkupRate");
    private final static QName _Pager_QNAME = new QName("", "Pager");
    private final static QName _Country_QNAME = new QName("", "Country");
    private final static QName _ExpectedDate_QNAME = new QName("", "ExpectedDate");
    private final static QName _ToModifiedDate_QNAME = new QName("", "ToModifiedDate");
    private final static QName _IsPrintItemsInGroup_QNAME = new QName("", "IsPrintItemsInGroup");
    private final static QName _FromTxnDate_QNAME = new QName("", "FromTxnDate");
    private final static QName _StatementDate_QNAME = new QName("", "StatementDate");
    private final static QName _Salutation_QNAME = new QName("", "Salutation");
    private final static QName _VendorMsg_QNAME = new QName("", "VendorMsg");
    private final static QName _TimeModified_QNAME = new QName("", "TimeModified");
    private final static QName _JobStatus_QNAME = new QName("", "JobStatus");
    private final static QName _BankNumber_QNAME = new QName("", "BankNumber");
    private final static QName _PricePercent_QNAME = new QName("", "PricePercent");
    private final static QName _PurchaseCost_QNAME = new QName("", "PurchaseCost");
    private final static QName _ServerDateTime_QNAME = new QName("", "ServerDateTime");
    private final static QName _StatementID_QNAME = new QName("", "StatementID");
    private final static QName _IsStatementWithParent_QNAME = new QName("", "IsStatementWithParent");
    private final static QName _FirstMonthIncomeTaxYear_QNAME = new QName("", "FirstMonthIncomeTaxYear");
    private final static QName _CreditCardNumber_QNAME = new QName("", "CreditCardNumber");
    private final static QName _FirstMonthFiscalYear_QNAME = new QName("", "FirstMonthFiscalYear");
    private final static QName _ToName_QNAME = new QName("", "ToName");
    private final static QName _IsTaxable_QNAME = new QName("", "IsTaxable");
    private final static QName _MajorVersion_QNAME = new QName("", "MajorVersion");
    private final static QName _StatementNumber_QNAME = new QName("", "StatementNumber");
    private final static QName _Ticket_QNAME = new QName("", "Ticket");
    private final static QName _DeliveryMethod_QNAME = new QName("", "DeliveryMethod");
    private final static QName _TxnLineID_QNAME = new QName("", "TxnLineID");
    private final static QName _OpenBalance_QNAME = new QName("", "OpenBalance");
    private final static QName _BalanceRemaining_QNAME = new QName("", "BalanceRemaining");
    private final static QName _FirstName_QNAME = new QName("", "FirstName");
    private final static QName _ItemDesc_QNAME = new QName("", "ItemDesc");
    private final static QName _CreditLimit_QNAME = new QName("", "CreditLimit");
    private final static QName _TxnDate_QNAME = new QName("", "TxnDate");
    private final static QName _AgencyPass_QNAME = new QName("", "AgencyPass");
    private final static QName _Amount_QNAME = new QName("", "Amount");
    private final static QName _MinorVersion_QNAME = new QName("", "MinorVersion");
    private final static QName _UserPass_QNAME = new QName("", "UserPass");
    private final static QName _OriginalAmount_QNAME = new QName("", "OriginalAmount");
    private final static QName _Mobile_QNAME = new QName("", "Mobile");
    private final static QName _DiscountRate_QNAME = new QName("", "DiscountRate");
    private final static QName _AuthID_QNAME = new QName("", "AuthID");
    private final static QName _ExpirationDate_QNAME = new QName("", "ExpirationDate");
    private final static QName _TargetParentID_QNAME = new QName("", "TargetParentID");
    private final static QName _ReleasedDate_QNAME = new QName("", "ReleasedDate");
    private final static QName _Initial_QNAME = new QName("", "Initial");
    private final static QName _Memo_QNAME = new QName("", "Memo");
    private final static QName _ToRefNumber_QNAME = new QName("", "ToRefNumber");
    private final static QName _ParentID_QNAME = new QName("", "ParentID");
    private final static QName _Addr3_QNAME = new QName("", "Addr3");
    private final static QName _AgencyParentID_QNAME = new QName("", "AgencyParentID");
    private final static QName _HiredDate_QNAME = new QName("", "HiredDate");
    private final static QName _Addr1_QNAME = new QName("", "Addr1");
    private final static QName _Email_QNAME = new QName("", "Email");
    private final static QName _Addr2_QNAME = new QName("", "Addr2");
    private final static QName _LegalCompanyName_QNAME = new QName("", "LegalCompanyName");
    private final static QName _ProductName_QNAME = new QName("", "ProductName");
    private final static QName _ReminderDate_QNAME = new QName("", "ReminderDate");
    private final static QName _PurchaseDesc_QNAME = new QName("", "PurchaseDesc");
    private final static QName _AverageCost_QNAME = new QName("", "AverageCost");
    private final static QName _RatePercent_QNAME = new QName("", "RatePercent");
    private final static QName _ToTxnDate_QNAME = new QName("", "ToTxnDate");
    private final static QName _FromRefNumber_QNAME = new QName("", "FromRefNumber");
    private final static QName _IsFinanceCharge_QNAME = new QName("", "IsFinanceCharge");
    private final static QName _StdDiscountDays_QNAME = new QName("", "StdDiscountDays");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _TimeCreated_QNAME = new QName("", "TimeCreated");
    private final static QName _Desc_QNAME = new QName("", "Desc");
    private final static QName _CompanyName_QNAME = new QName("", "CompanyName");
    private final static QName _TotalValue_QNAME = new QName("", "TotalValue");
    private final static QName _ServiceDate_QNAME = new QName("", "ServiceDate");
    private final static QName _FOB_QNAME = new QName("", "FOB");
    private final static QName _IsToBePrinted_QNAME = new QName("", "IsToBePrinted");
    private final static QName _ResaleNumber_QNAME = new QName("", "ResaleNumber");
    private final static QName _UserLogin_QNAME = new QName("", "UserLogin");
    private final static QName _LastCheckNumber_QNAME = new QName("", "LastCheckNumber");
    private final static QName _TxnNumber_QNAME = new QName("", "TxnNumber");
    private final static QName _WageType_QNAME = new QName("", "WageType");
    private final static QName _PaidStatus_QNAME = new QName("", "PaidStatus");
    private final static QName _InventoryDate_QNAME = new QName("", "InventoryDate");
    private final static QName _AmountDue_QNAME = new QName("", "AmountDue");
    private final static QName _RefNumber_QNAME = new QName("", "RefNumber");
    private final static QName _EditSequence_QNAME = new QName("", "EditSequence");
    private final static QName _Duration_QNAME = new QName("", "Duration");
    private final static QName _AppVer_QNAME = new QName("", "AppVer");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _OpenBalanceDate_QNAME = new QName("", "OpenBalanceDate");
    private final static QName _QuantityOnHand_QNAME = new QName("", "QuantityOnHand");
    private final static QName _AppendNotes_QNAME = new QName("", "AppendNotes");
    private final static QName _StdDueDays_QNAME = new QName("", "StdDueDays");
    private final static QName _DiscountPct_QNAME = new QName("", "DiscountPct");
    private final static QName _TotalBalance_QNAME = new QName("", "TotalBalance");
    private final static QName _CompanyEmailForCustomer_QNAME = new QName("", "CompanyEmailForCustomer");
    private final static QName _JobEndDate_QNAME = new QName("", "JobEndDate");
    private final static QName _AltPhone_QNAME = new QName("", "AltPhone");
    private final static QName _JobDesc_QNAME = new QName("", "JobDesc");
    private final static QName _OwnerID_QNAME = new QName("", "OwnerID");
    private final static QName _Price_QNAME = new QName("", "Price");
    private final static QName _State_QNAME = new QName("", "State");
    private final static QName _LastName_QNAME = new QName("", "LastName");
    private final static QName _Balance_QNAME = new QName("", "Balance");
    private final static QName _Operator_QNAME = new QName("", "Operator");
    private final static QName _QuantityOnOrder_QNAME = new QName("", "QuantityOnOrder");
    private final static QName _DoneStatus_QNAME = new QName("", "DoneStatus");
    private final static QName _CompanyWebSite_QNAME = new QName("", "CompanyWebSite");
    private final static QName _VendorTaxIdent_QNAME = new QName("", "VendorTaxIdent");
    private final static QName _IsActive_QNAME = new QName("", "IsActive");
    private final static QName _SuggestedDiscountDate_QNAME = new QName("", "SuggestedDiscountDate");
    private final static QName _PostalCode_QNAME = new QName("", "PostalCode");
    private final static QName _Cost_QNAME = new QName("", "Cost");
    private final static QName _AuthPass_QNAME = new QName("", "AuthPass");
    private final static QName _FullNameWithChildren_QNAME = new QName("", "FullNameWithChildren");
    private final static QName _SalesPrice_QNAME = new QName("", "SalesPrice");
    private final static QName _FromName_QNAME = new QName("", "FromName");
    private final static QName _SuggestedDiscountAmount_QNAME = new QName("", "SuggestedDiscountAmount");
    private final static QName _SalesTaxTotal_QNAME = new QName("", "SalesTaxTotal");
    private final static QName _MarkupRatePercent_QNAME = new QName("", "MarkupRatePercent");
    private final static QName _Language_QNAME = new QName("", "Language");
    private final static QName _IsVendorEligibleFor1099_QNAME = new QName("", "IsVendorEligibleFor1099");
    private final static QName _Phone_QNAME = new QName("", "Phone");
    private final static QName _DiscountDayOfMonth_QNAME = new QName("", "DiscountDayOfMonth");
    private final static QName _TaxRate_QNAME = new QName("", "TaxRate");
    private final static QName _DueDate_QNAME = new QName("", "DueDate");
    private final static QName _ExternalGUID_QNAME = new QName("", "ExternalGUID");
    private final static QName _ChargeNumber_QNAME = new QName("", "ChargeNumber");
    private final static QName _IsPending_QNAME = new QName("", "IsPending");
    private final static QName _Notes_QNAME = new QName("", "Notes");
    private final static QName _IsBillable_QNAME = new QName("", "IsBillable");
    private final static QName _SalesTaxPercentage_QNAME = new QName("", "SalesTaxPercentage");
    private final static QName _AppliedAmount_QNAME = new QName("", "AppliedAmount");
    private final static QName _Quantity_QNAME = new QName("", "Quantity");
    private final static QName _PrintAs_QNAME = new QName("", "PrintAs");
    private final static QName _SupportedQBXMLVersion_QNAME = new QName("", "SupportedQBXMLVersion");
    private final static QName _IsDone_QNAME = new QName("", "IsDone");
    private final static QName _TotalAmount_QNAME = new QName("", "TotalAmount");
    private final static QName _CheckNumber_QNAME = new QName("", "CheckNumber");
    private final static QName _IsBilled_QNAME = new QName("", "IsBilled");
    private final static QName _MiddleName_QNAME = new QName("", "MiddleName");
    private final static QName _SalesDesc_QNAME = new QName("", "SalesDesc");
    private final static QName _AccountType_QNAME = new QName("", "AccountType");
    private final static QName _DiscountRatePercent_QNAME = new QName("", "DiscountRatePercent");
    private final static QName _EmployeeType_QNAME = new QName("", "EmployeeType");
    private final static QName _AccountNumber_QNAME = new QName("", "AccountNumber");
    private final static QName _Contact_QNAME = new QName("", "Contact");
    private final static QName _SSN_QNAME = new QName("", "SSN");
    private final static QName _Sublevel_QNAME = new QName("", "Sublevel");
    private final static QName _ListID_QNAME = new QName("", "ListID");
    private final static QName _FullName_QNAME = new QName("", "FullName");
    private final static QName _Fax_QNAME = new QName("", "Fax");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hourtimesheet.desktop
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerRet }
     * 
     */
    public CustomerRet createCustomerRet() {
        return new CustomerRet();
    }

    /**
     * Create an instance of {@link ParentRef }
     * 
     */
    public ParentRef createParentRef() {
        return new ParentRef();
    }

    /**
     * Create an instance of {@link BillAddress }
     * 
     */
    public BillAddress createBillAddress() {
        return new BillAddress();
    }

    /**
     * Create an instance of {@link ShipAddress }
     * 
     */
    public ShipAddress createShipAddress() {
        return new ShipAddress();
    }

    /**
     * Create an instance of {@link CustomerTypeRef }
     * 
     */
    public CustomerTypeRef createCustomerTypeRef() {
        return new CustomerTypeRef();
    }

    /**
     * Create an instance of {@link TermsRef }
     * 
     */
    public TermsRef createTermsRef() {
        return new TermsRef();
    }

    /**
     * Create an instance of {@link SalesRepRef }
     * 
     */
    public SalesRepRef createSalesRepRef() {
        return new SalesRepRef();
    }

    /**
     * Create an instance of {@link SalesTaxCodeRef }
     * 
     */
    public SalesTaxCodeRef createSalesTaxCodeRef() {
        return new SalesTaxCodeRef();
    }

    /**
     * Create an instance of {@link ItemSalesTaxRef }
     * 
     */
    public ItemSalesTaxRef createItemSalesTaxRef() {
        return new ItemSalesTaxRef();
    }

    /**
     * Create an instance of {@link JobTypeRef }
     * 
     */
    public JobTypeRef createJobTypeRef() {
        return new JobTypeRef();
    }

    /**
     * Create an instance of {@link CustomerAdd }
     * 
     */
    public CustomerAdd createCustomerAdd() {
        return new CustomerAdd();
    }

    /**
     * Create an instance of {@link VendorTypeRef }
     * 
     */
    public VendorTypeRef createVendorTypeRef() {
        return new VendorTypeRef();
    }

    /**
     * Create an instance of {@link EmployeeAddress }
     * 
     */
    public EmployeeAddress createEmployeeAddress() {
        return new EmployeeAddress();
    }

    /**
     * Create an instance of {@link SimpleListObjRef }
     * 
     */
    public SimpleListObjRef createSimpleListObjRef() {
        return new SimpleListObjRef();
    }

    /**
     * Create an instance of {@link VendorListObjRef }
     * 
     */
    public VendorListObjRef createVendorListObjRef() {
        return new VendorListObjRef();
    }

    /**
     * Create an instance of {@link CustomerMsgRef }
     * 
     */
    public CustomerMsgRef createCustomerMsgRef() {
        return new CustomerMsgRef();
    }

    /**
     * Create an instance of {@link NameRangeFilter }
     * 
     */
    public NameRangeFilter createNameRangeFilter() {
        return new NameRangeFilter();
    }

    /**
     * Create an instance of {@link OtherNameAddress }
     * 
     */
    public OtherNameAddress createOtherNameAddress() {
        return new OtherNameAddress();
    }

    /**
     * Create an instance of {@link ARAccountRef }
     * 
     */
    public ARAccountRef createARAccountRef() {
        return new ARAccountRef();
    }

    /**
     * Create an instance of {@link CustomerRef }
     * 
     */
    public CustomerRef createCustomerRef() {
        return new CustomerRef();
    }

    /**
     * Create an instance of {@link SalesAndPurchaseMod }
     * 
     */
    public SalesAndPurchaseMod createSalesAndPurchaseMod() {
        return new SalesAndPurchaseMod();
    }

    /**
     * Create an instance of {@link IncomeAccountRef }
     * 
     */
    public IncomeAccountRef createIncomeAccountRef() {
        return new IncomeAccountRef();
    }

    /**
     * Create an instance of {@link ExpenseAccountRef }
     * 
     */
    public ExpenseAccountRef createExpenseAccountRef() {
        return new ExpenseAccountRef();
    }

    /**
     * Create an instance of {@link PrefVendorRef }
     * 
     */
    public PrefVendorRef createPrefVendorRef() {
        return new PrefVendorRef();
    }

    /**
     * Create an instance of {@link ItemGroupRef }
     * 
     */
    public ItemGroupRef createItemGroupRef() {
        return new ItemGroupRef();
    }

    /**
     * Create an instance of {@link EntityListObjRef }
     * 
     */
    public EntityListObjRef createEntityListObjRef() {
        return new EntityListObjRef();
    }

    /**
     * Create an instance of {@link TxnDateRangeFilter }
     * 
     */
    public TxnDateRangeFilter createTxnDateRangeFilter() {
        return new TxnDateRangeFilter();
    }

    /**
     * Create an instance of {@link ShipToEntityRef }
     * 
     */
    public ShipToEntityRef createShipToEntityRef() {
        return new ShipToEntityRef();
    }

    /**
     * Create an instance of {@link CustomerListObjRef }
     * 
     */
    public CustomerListObjRef createCustomerListObjRef() {
        return new CustomerListObjRef();
    }

    /**
     * Create an instance of {@link VendorRet }
     * 
     */
    public VendorRet createVendorRet() {
        return new VendorRet();
    }

    /**
     * Create an instance of {@link VendorAddress }
     * 
     */
    public VendorAddress createVendorAddress() {
        return new VendorAddress();
    }

    /**
     * Create an instance of {@link VendorAdd }
     * 
     */
    public VendorAdd createVendorAdd() {
        return new VendorAdd();
    }

    /**
     * Create an instance of {@link EmployeeMod }
     * 
     */
    public EmployeeMod createEmployeeMod() {
        return new EmployeeMod();
    }

    /**
     * Create an instance of {@link VendorRef }
     * 
     */
    public VendorRef createVendorRef() {
        return new VendorRef();
    }

    /**
     * Create an instance of {@link ListObjRef }
     * 
     */
    public ListObjRef createListObjRef() {
        return new ListObjRef();
    }

    /**
     * Create an instance of {@link SalesOrPurchaseMod }
     * 
     */
    public SalesOrPurchaseMod createSalesOrPurchaseMod() {
        return new SalesOrPurchaseMod();
    }

    /**
     * Create an instance of {@link AccountRef }
     * 
     */
    public AccountRef createAccountRef() {
        return new AccountRef();
    }

    /**
     * Create an instance of {@link VendorMod }
     * 
     */
    public VendorMod createVendorMod() {
        return new VendorMod();
    }

    /**
     * Create an instance of {@link RefNumberFilter }
     * 
     */
    public RefNumberFilter createRefNumberFilter() {
        return new RefNumberFilter();
    }

    /**
     * Create an instance of {@link QBXML }
     * 
     */
    public QBXML createQBXML() {
        return new QBXML();
    }

    /**
     * Create an instance of {@link QBXMLMsgsRs }
     * 
     */
    public QBXMLMsgsRs createQBXMLMsgsRs() {
        return new QBXMLMsgsRs();
    }

    /**
     * Create an instance of {@link PaymentMethodRef }
     * 
     */
    public PaymentMethodRef createPaymentMethodRef() {
        return new PaymentMethodRef();
    }

    /**
     * Create an instance of {@link EntityRef }
     * 
     */
    public EntityRef createEntityRef() {
        return new EntityRef();
    }

    /**
     * Create an instance of {@link AccountFilter }
     * 
     */
    public AccountFilter createAccountFilter() {
        return new AccountFilter();
    }

    /**
     * Create an instance of {@link TaxVendorRef }
     * 
     */
    public TaxVendorRef createTaxVendorRef() {
        return new TaxVendorRef();
    }

    /**
     * Create an instance of {@link EmployeeRef }
     * 
     */
    public EmployeeRef createEmployeeRef() {
        return new EmployeeRef();
    }

    /**
     * Create an instance of {@link TimeTrackingRet }
     * 
     */
    public TimeTrackingRet createTimeTrackingRet() {
        return new TimeTrackingRet();
    }

    /**
     * Create an instance of {@link ItemServiceRef }
     * 
     */
    public ItemServiceRef createItemServiceRef() {
        return new ItemServiceRef();
    }

    /**
     * Create an instance of {@link ClassRef }
     * 
     */
    public ClassRef createClassRef() {
        return new ClassRef();
    }

    /**
     * Create an instance of {@link PayrollItemWageRef }
     * 
     */
    public PayrollItemWageRef createPayrollItemWageRef() {
        return new PayrollItemWageRef();
    }

    /**
     * Create an instance of {@link TimeTrackingAdd }
     * 
     */
    public TimeTrackingAdd createTimeTrackingAdd() {
        return new TimeTrackingAdd();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PayeeEntityRef }
     * 
     */
    public PayeeEntityRef createPayeeEntityRef() {
        return new PayeeEntityRef();
    }

    /**
     * Create an instance of {@link QBXMLMsgsRq }
     * 
     */
    public QBXMLMsgsRq createQBXMLMsgsRq() {
        return new QBXMLMsgsRq();
    }

    /**
     * Create an instance of {@link CustomerQueryRqType }
     * 
     */
    public CustomerQueryRqType createCustomerQueryRqType() {
        return new CustomerQueryRqType();
    }

    /**
     * Create an instance of {@link EmployeeQueryRqType }
     * 
     */
    public EmployeeQueryRqType createEmployeeQueryRqType() {
        return new EmployeeQueryRqType();
    }

    /**
     * Create an instance of {@link VendorQueryRqType }
     * 
     */
    public VendorQueryRqType createVendorQueryRqType() {
        return new VendorQueryRqType();
    }

    /**
     * Create an instance of {@link ClassQueryRqType }
     * 
     */
    public ClassQueryRqType createClassQueryRqType() {
        return new ClassQueryRqType();
    }

    /**
     * Create an instance of {@link ItemServiceQueryRqType }
     * 
     */
    public ItemServiceQueryRqType createItemServiceQueryRqType() {
        return new ItemServiceQueryRqType();
    }

    /**
     * Create an instance of {@link PayrollItemWageQueryRqType }
     * 
     */
    public PayrollItemWageQueryRqType createPayrollItemWageQueryRqType() {
        return new PayrollItemWageQueryRqType();
    }

    /**
     * Create an instance of {@link TimeTrackingAddRqType }
     * 
     */
    public TimeTrackingAddRqType createTimeTrackingAddRqType() {
        return new TimeTrackingAddRqType();
    }

    /**
     * Create an instance of {@link EmployeeRet }
     * 
     */
    public EmployeeRet createEmployeeRet() {
        return new EmployeeRet();
    }

    /**
     * Create an instance of {@link EmployeeAdd }
     * 
     */
    public EmployeeAdd createEmployeeAdd() {
        return new EmployeeAdd();
    }

    /**
     * Create an instance of {@link ItemServiceRet }
     * 
     */
    public ItemServiceRet createItemServiceRet() {
        return new ItemServiceRet();
    }

    /**
     * Create an instance of {@link SalesOrPurchase }
     * 
     */
    public SalesOrPurchase createSalesOrPurchase() {
        return new SalesOrPurchase();
    }

    /**
     * Create an instance of {@link SalesAndPurchase }
     * 
     */
    public SalesAndPurchase createSalesAndPurchase() {
        return new SalesAndPurchase();
    }

    /**
     * Create an instance of {@link ItemServiceAdd }
     * 
     */
    public ItemServiceAdd createItemServiceAdd() {
        return new ItemServiceAdd();
    }

    /**
     * Create an instance of {@link DepositToAccountRef }
     * 
     */
    public DepositToAccountRef createDepositToAccountRef() {
        return new DepositToAccountRef();
    }

    /**
     * Create an instance of {@link ClassRet }
     * 
     */
    public ClassRet createClassRet() {
        return new ClassRet();
    }

    /**
     * Create an instance of {@link ClassAdd }
     * 
     */
    public ClassAdd createClassAdd() {
        return new ClassAdd();
    }

    /**
     * Create an instance of {@link ItemRef }
     * 
     */
    public ItemRef createItemRef() {
        return new ItemRef();
    }

    /**
     * Create an instance of {@link SalesRepEntityRef }
     * 
     */
    public SalesRepEntityRef createSalesRepEntityRef() {
        return new SalesRepEntityRef();
    }

    /**
     * Create an instance of {@link COGSAccountRef }
     * 
     */
    public COGSAccountRef createCOGSAccountRef() {
        return new COGSAccountRef();
    }

    /**
     * Create an instance of {@link ErrorRecovery }
     * 
     */
    public ErrorRecovery createErrorRecovery() {
        return new ErrorRecovery();
    }

    /**
     * Create an instance of {@link LegalAddress }
     * 
     */
    public LegalAddress createLegalAddress() {
        return new LegalAddress();
    }

    /**
     * Create an instance of {@link NameFilter }
     * 
     */
    public NameFilter createNameFilter() {
        return new NameFilter();
    }

    /**
     * Create an instance of {@link PayrollItemWageRet }
     * 
     */
    public PayrollItemWageRet createPayrollItemWageRet() {
        return new PayrollItemWageRet();
    }

    /**
     * Create an instance of {@link CompanyAddressForCustomer }
     * 
     */
    public CompanyAddressForCustomer createCompanyAddressForCustomer() {
        return new CompanyAddressForCustomer();
    }

    /**
     * Create an instance of {@link ModifiedDateRangeFilter }
     * 
     */
    public ModifiedDateRangeFilter createModifiedDateRangeFilter() {
        return new ModifiedDateRangeFilter();
    }

    /**
     * Create an instance of {@link ClassMod }
     * 
     */
    public ClassMod createClassMod() {
        return new ClassMod();
    }

    /**
     * Create an instance of {@link EntityFilter }
     * 
     */
    public EntityFilter createEntityFilter() {
        return new EntityFilter();
    }

    /**
     * Create an instance of {@link RefundFromAccountRef }
     * 
     */
    public RefundFromAccountRef createRefundFromAccountRef() {
        return new RefundFromAccountRef();
    }

    /**
     * Create an instance of {@link ItemServiceMod }
     * 
     */
    public ItemServiceMod createItemServiceMod() {
        return new ItemServiceMod();
    }

    /**
     * Create an instance of {@link TotalBalanceFilter }
     * 
     */
    public TotalBalanceFilter createTotalBalanceFilter() {
        return new TotalBalanceFilter();
    }

    /**
     * Create an instance of {@link TimeTrackingEntityFilter }
     * 
     */
    public TimeTrackingEntityFilter createTimeTrackingEntityFilter() {
        return new TimeTrackingEntityFilter();
    }

    /**
     * Create an instance of {@link AssetAccountRef }
     * 
     */
    public AssetAccountRef createAssetAccountRef() {
        return new AssetAccountRef();
    }

    /**
     * Create an instance of {@link RefNumberRangeFilter }
     * 
     */
    public RefNumberRangeFilter createRefNumberRangeFilter() {
        return new RefNumberRangeFilter();
    }

    /**
     * Create an instance of {@link DiscountAccountRef }
     * 
     */
    public DiscountAccountRef createDiscountAccountRef() {
        return new DiscountAccountRef();
    }

    /**
     * Create an instance of {@link CustomerSalesTaxCodeRef }
     * 
     */
    public CustomerSalesTaxCodeRef createCustomerSalesTaxCodeRef() {
        return new CustomerSalesTaxCodeRef();
    }

    /**
     * Create an instance of {@link ShipMethodRef }
     * 
     */
    public ShipMethodRef createShipMethodRef() {
        return new ShipMethodRef();
    }

    /**
     * Create an instance of {@link CustomerMod }
     * 
     */
    public CustomerMod createCustomerMod() {
        return new CustomerMod();
    }

    /**
     * Create an instance of {@link ItemServiceQueryRsType }
     * 
     */
    public ItemServiceQueryRsType createItemServiceQueryRsType() {
        return new ItemServiceQueryRsType();
    }

    /**
     * Create an instance of {@link ClassQueryRsType }
     * 
     */
    public ClassQueryRsType createClassQueryRsType() {
        return new ClassQueryRsType();
    }

    /**
     * Create an instance of {@link PayrollItemWageQueryRsType }
     * 
     */
    public PayrollItemWageQueryRsType createPayrollItemWageQueryRsType() {
        return new PayrollItemWageQueryRsType();
    }

    /**
     * Create an instance of {@link VendorQueryRsType }
     * 
     */
    public VendorQueryRsType createVendorQueryRsType() {
        return new VendorQueryRsType();
    }

    /**
     * Create an instance of {@link CustomerQueryRsType }
     * 
     */
    public CustomerQueryRsType createCustomerQueryRsType() {
        return new CustomerQueryRsType();
    }

    /**
     * Create an instance of {@link TimeTrackingAddRsType }
     * 
     */
    public TimeTrackingAddRsType createTimeTrackingAddRsType() {
        return new TimeTrackingAddRsType();
    }

    /**
     * Create an instance of {@link EmployeeQueryRs }
     * 
     */
    public EmployeeQueryRs createEmployeeQueryRs() {
        return new EmployeeQueryRs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PONumber")
    public JAXBElement<String> createPONumber(String value) {
        return new JAXBElement<String>(_PONumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AgencyLogin")
    public JAXBElement<String> createAgencyLogin(String value) {
        return new JAXBElement<String>(_AgencyLogin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CompanyID")
    public JAXBElement<String> createCompanyID(String value) {
        return new JAXBElement<String>(_CompanyID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromModifiedDate")
    public JAXBElement<String> createFromModifiedDate(String value) {
        return new JAXBElement<String>(_FromModifiedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateMacro")
    public JAXBElement<String> createDateMacro(String value) {
        return new JAXBElement<String>(_DateMacro_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchCriterion")
    public JAXBElement<String> createMatchCriterion(String value) {
        return new JAXBElement<String>(_MatchCriterion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditAmount")
    public JAXBElement<String> createCreditAmount(String value) {
        return new JAXBElement<String>(_CreditAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PaymentAmount")
    public JAXBElement<String> createPaymentAmount(String value) {
        return new JAXBElement<String>(_PaymentAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DetailAccountType")
    public JAXBElement<String> createDetailAccountType(String value) {
        return new JAXBElement<String>(_DetailAccountType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaxReturned")
    public JAXBElement<Integer> createMaxReturned(Integer value) {
        return new JAXBElement<Integer>(_MaxReturned_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ActiveStatus", defaultValue = "ActiveOnly")
    public JAXBElement<String> createActiveStatus(String value) {
        return new JAXBElement<String>(_ActiveStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReorderPoint")
    public JAXBElement<String> createReorderPoint(String value) {
        return new JAXBElement<String>(_ReorderPoint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppID")
    public JAXBElement<String> createAppID(String value) {
        return new JAXBElement<String>(_AppID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClientDateTime")
    public JAXBElement<String> createClientDateTime(String value) {
        return new JAXBElement<String>(_ClientDateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IncludeLineItems")
    public JAXBElement<String> createIncludeLineItems(String value) {
        return new JAXBElement<String>(_IncludeLineItems_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DayOfMonthDue")
    public JAXBElement<BigInteger> createDayOfMonthDue(BigInteger value) {
        return new JAXBElement<BigInteger>(_DayOfMonthDue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpenAmount")
    public JAXBElement<String> createOpenAmount(String value) {
        return new JAXBElement<String>(_OpenAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NameOnCheck")
    public JAXBElement<String> createNameOnCheck(String value) {
        return new JAXBElement<String>(_NameOnCheck_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InstallationID")
    public JAXBElement<String> createInstallationID(String value) {
        return new JAXBElement<String>(_InstallationID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TargetLogin")
    public JAXBElement<String> createTargetLogin(String value) {
        return new JAXBElement<String>(_TargetLogin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxnType")
    public JAXBElement<String> createTxnType(String value) {
        return new JAXBElement<String>(_TxnType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DueNextMonthDays")
    public JAXBElement<BigInteger> createDueNextMonthDays(BigInteger value) {
        return new JAXBElement<BigInteger>(_DueNextMonthDays_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Rate")
    public JAXBElement<String> createRate(String value) {
        return new JAXBElement<String>(_Rate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JobProjectedEndDate")
    public JAXBElement<String> createJobProjectedEndDate(String value) {
        return new JAXBElement<String>(_JobProjectedEndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Subtotal")
    public JAXBElement<String> createSubtotal(String value) {
        return new JAXBElement<String>(_Subtotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CompanyType")
    public JAXBElement<String> createCompanyType(String value) {
        return new JAXBElement<String>(_CompanyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShipDate")
    public JAXBElement<String> createShipDate(String value) {
        return new JAXBElement<String>(_ShipDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AltContact")
    public JAXBElement<String> createAltContact(String value) {
        return new JAXBElement<String>(_AltContact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DiscountAmount")
    public JAXBElement<String> createDiscountAmount(String value) {
        return new JAXBElement<String>(_DiscountAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxnID")
    public JAXBElement<String> createTxnID(String value) {
        return new JAXBElement<String>(_TxnID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Suffix")
    public JAXBElement<String> createSuffix(String value) {
        return new JAXBElement<String>(_Suffix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JobStartDate")
    public JAXBElement<String> createJobStartDate(String value) {
        return new JAXBElement<String>(_JobStartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BillableStatus")
    public JAXBElement<String> createBillableStatus(String value) {
        return new JAXBElement<String>(_BillableStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MarkupRate")
    public JAXBElement<String> createMarkupRate(String value) {
        return new JAXBElement<String>(_MarkupRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pager")
    public JAXBElement<String> createPager(String value) {
        return new JAXBElement<String>(_Pager_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpectedDate")
    public JAXBElement<String> createExpectedDate(String value) {
        return new JAXBElement<String>(_ExpectedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToModifiedDate")
    public JAXBElement<String> createToModifiedDate(String value) {
        return new JAXBElement<String>(_ToModifiedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsPrintItemsInGroup")
    public JAXBElement<String> createIsPrintItemsInGroup(String value) {
        return new JAXBElement<String>(_IsPrintItemsInGroup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromTxnDate")
    public JAXBElement<String> createFromTxnDate(String value) {
        return new JAXBElement<String>(_FromTxnDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StatementDate")
    public JAXBElement<String> createStatementDate(String value) {
        return new JAXBElement<String>(_StatementDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Salutation")
    public JAXBElement<String> createSalutation(String value) {
        return new JAXBElement<String>(_Salutation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VendorMsg")
    public JAXBElement<String> createVendorMsg(String value) {
        return new JAXBElement<String>(_VendorMsg_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeModified")
    public JAXBElement<String> createTimeModified(String value) {
        return new JAXBElement<String>(_TimeModified_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JobStatus", defaultValue = "None")
    public JAXBElement<String> createJobStatus(String value) {
        return new JAXBElement<String>(_JobStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BankNumber")
    public JAXBElement<String> createBankNumber(String value) {
        return new JAXBElement<String>(_BankNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PricePercent")
    public JAXBElement<String> createPricePercent(String value) {
        return new JAXBElement<String>(_PricePercent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PurchaseCost")
    public JAXBElement<String> createPurchaseCost(String value) {
        return new JAXBElement<String>(_PurchaseCost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServerDateTime")
    public JAXBElement<String> createServerDateTime(String value) {
        return new JAXBElement<String>(_ServerDateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StatementID")
    public JAXBElement<String> createStatementID(String value) {
        return new JAXBElement<String>(_StatementID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsStatementWithParent")
    public JAXBElement<String> createIsStatementWithParent(String value) {
        return new JAXBElement<String>(_IsStatementWithParent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstMonthIncomeTaxYear")
    public JAXBElement<String> createFirstMonthIncomeTaxYear(String value) {
        return new JAXBElement<String>(_FirstMonthIncomeTaxYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditCardNumber")
    public JAXBElement<String> createCreditCardNumber(String value) {
        return new JAXBElement<String>(_CreditCardNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstMonthFiscalYear")
    public JAXBElement<String> createFirstMonthFiscalYear(String value) {
        return new JAXBElement<String>(_FirstMonthFiscalYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToName")
    public JAXBElement<String> createToName(String value) {
        return new JAXBElement<String>(_ToName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsTaxable")
    public JAXBElement<String> createIsTaxable(String value) {
        return new JAXBElement<String>(_IsTaxable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MajorVersion")
    public JAXBElement<String> createMajorVersion(String value) {
        return new JAXBElement<String>(_MajorVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StatementNumber")
    public JAXBElement<String> createStatementNumber(String value) {
        return new JAXBElement<String>(_StatementNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Ticket")
    public JAXBElement<String> createTicket(String value) {
        return new JAXBElement<String>(_Ticket_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeliveryMethod", defaultValue = "Print")
    public JAXBElement<String> createDeliveryMethod(String value) {
        return new JAXBElement<String>(_DeliveryMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxnLineID")
    public JAXBElement<String> createTxnLineID(String value) {
        return new JAXBElement<String>(_TxnLineID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpenBalance")
    public JAXBElement<String> createOpenBalance(String value) {
        return new JAXBElement<String>(_OpenBalance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BalanceRemaining")
    public JAXBElement<String> createBalanceRemaining(String value) {
        return new JAXBElement<String>(_BalanceRemaining_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ItemDesc")
    public JAXBElement<String> createItemDesc(String value) {
        return new JAXBElement<String>(_ItemDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditLimit")
    public JAXBElement<String> createCreditLimit(String value) {
        return new JAXBElement<String>(_CreditLimit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxnDate")
    public JAXBElement<String> createTxnDate(String value) {
        return new JAXBElement<String>(_TxnDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AgencyPass")
    public JAXBElement<String> createAgencyPass(String value) {
        return new JAXBElement<String>(_AgencyPass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Amount")
    public JAXBElement<String> createAmount(String value) {
        return new JAXBElement<String>(_Amount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MinorVersion")
    public JAXBElement<String> createMinorVersion(String value) {
        return new JAXBElement<String>(_MinorVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserPass")
    public JAXBElement<String> createUserPass(String value) {
        return new JAXBElement<String>(_UserPass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OriginalAmount")
    public JAXBElement<String> createOriginalAmount(String value) {
        return new JAXBElement<String>(_OriginalAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Mobile")
    public JAXBElement<String> createMobile(String value) {
        return new JAXBElement<String>(_Mobile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DiscountRate")
    public JAXBElement<String> createDiscountRate(String value) {
        return new JAXBElement<String>(_DiscountRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthID")
    public JAXBElement<String> createAuthID(String value) {
        return new JAXBElement<String>(_AuthID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpirationDate")
    public JAXBElement<String> createExpirationDate(String value) {
        return new JAXBElement<String>(_ExpirationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TargetParentID")
    public JAXBElement<String> createTargetParentID(String value) {
        return new JAXBElement<String>(_TargetParentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReleasedDate")
    public JAXBElement<String> createReleasedDate(String value) {
        return new JAXBElement<String>(_ReleasedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Initial")
    public JAXBElement<String> createInitial(String value) {
        return new JAXBElement<String>(_Initial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Memo")
    public JAXBElement<String> createMemo(String value) {
        return new JAXBElement<String>(_Memo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToRefNumber")
    public JAXBElement<String> createToRefNumber(String value) {
        return new JAXBElement<String>(_ToRefNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ParentID")
    public JAXBElement<String> createParentID(String value) {
        return new JAXBElement<String>(_ParentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Addr3")
    public JAXBElement<String> createAddr3(String value) {
        return new JAXBElement<String>(_Addr3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AgencyParentID")
    public JAXBElement<String> createAgencyParentID(String value) {
        return new JAXBElement<String>(_AgencyParentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HiredDate")
    public JAXBElement<String> createHiredDate(String value) {
        return new JAXBElement<String>(_HiredDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Addr1")
    public JAXBElement<String> createAddr1(String value) {
        return new JAXBElement<String>(_Addr1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Addr2")
    public JAXBElement<String> createAddr2(String value) {
        return new JAXBElement<String>(_Addr2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LegalCompanyName")
    public JAXBElement<String> createLegalCompanyName(String value) {
        return new JAXBElement<String>(_LegalCompanyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProductName")
    public JAXBElement<String> createProductName(String value) {
        return new JAXBElement<String>(_ProductName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReminderDate")
    public JAXBElement<String> createReminderDate(String value) {
        return new JAXBElement<String>(_ReminderDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PurchaseDesc")
    public JAXBElement<String> createPurchaseDesc(String value) {
        return new JAXBElement<String>(_PurchaseDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AverageCost")
    public JAXBElement<String> createAverageCost(String value) {
        return new JAXBElement<String>(_AverageCost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatePercent")
    public JAXBElement<String> createRatePercent(String value) {
        return new JAXBElement<String>(_RatePercent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToTxnDate")
    public JAXBElement<String> createToTxnDate(String value) {
        return new JAXBElement<String>(_ToTxnDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromRefNumber")
    public JAXBElement<String> createFromRefNumber(String value) {
        return new JAXBElement<String>(_FromRefNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsFinanceCharge")
    public JAXBElement<String> createIsFinanceCharge(String value) {
        return new JAXBElement<String>(_IsFinanceCharge_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StdDiscountDays")
    public JAXBElement<BigInteger> createStdDiscountDays(BigInteger value) {
        return new JAXBElement<BigInteger>(_StdDiscountDays_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeCreated")
    public JAXBElement<String> createTimeCreated(String value) {
        return new JAXBElement<String>(_TimeCreated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Desc")
    public JAXBElement<String> createDesc(String value) {
        return new JAXBElement<String>(_Desc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CompanyName")
    public JAXBElement<String> createCompanyName(String value) {
        return new JAXBElement<String>(_CompanyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalValue")
    public JAXBElement<String> createTotalValue(String value) {
        return new JAXBElement<String>(_TotalValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceDate")
    public JAXBElement<String> createServiceDate(String value) {
        return new JAXBElement<String>(_ServiceDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FOB")
    public JAXBElement<String> createFOB(String value) {
        return new JAXBElement<String>(_FOB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsToBePrinted")
    public JAXBElement<String> createIsToBePrinted(String value) {
        return new JAXBElement<String>(_IsToBePrinted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResaleNumber")
    public JAXBElement<String> createResaleNumber(String value) {
        return new JAXBElement<String>(_ResaleNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserLogin")
    public JAXBElement<String> createUserLogin(String value) {
        return new JAXBElement<String>(_UserLogin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastCheckNumber")
    public JAXBElement<String> createLastCheckNumber(String value) {
        return new JAXBElement<String>(_LastCheckNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxnNumber")
    public JAXBElement<BigInteger> createTxnNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_TxnNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WageType")
    public JAXBElement<String> createWageType(String value) {
        return new JAXBElement<String>(_WageType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PaidStatus", defaultValue = "All")
    public JAXBElement<String> createPaidStatus(String value) {
        return new JAXBElement<String>(_PaidStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InventoryDate")
    public JAXBElement<String> createInventoryDate(String value) {
        return new JAXBElement<String>(_InventoryDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AmountDue")
    public JAXBElement<String> createAmountDue(String value) {
        return new JAXBElement<String>(_AmountDue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RefNumber")
    public JAXBElement<String> createRefNumber(String value) {
        return new JAXBElement<String>(_RefNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EditSequence")
    public JAXBElement<String> createEditSequence(String value) {
        return new JAXBElement<String>(_EditSequence_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Duration")
    public JAXBElement<String> createDuration(String value) {
        return new JAXBElement<String>(_Duration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppVer")
    public JAXBElement<String> createAppVer(String value) {
        return new JAXBElement<String>(_AppVer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpenBalanceDate")
    public JAXBElement<String> createOpenBalanceDate(String value) {
        return new JAXBElement<String>(_OpenBalanceDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityOnHand")
    public JAXBElement<String> createQuantityOnHand(String value) {
        return new JAXBElement<String>(_QuantityOnHand_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppendNotes")
    public JAXBElement<String> createAppendNotes(String value) {
        return new JAXBElement<String>(_AppendNotes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StdDueDays")
    public JAXBElement<BigInteger> createStdDueDays(BigInteger value) {
        return new JAXBElement<BigInteger>(_StdDueDays_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DiscountPct")
    public JAXBElement<String> createDiscountPct(String value) {
        return new JAXBElement<String>(_DiscountPct_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalBalance")
    public JAXBElement<String> createTotalBalance(String value) {
        return new JAXBElement<String>(_TotalBalance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CompanyEmailForCustomer")
    public JAXBElement<String> createCompanyEmailForCustomer(String value) {
        return new JAXBElement<String>(_CompanyEmailForCustomer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JobEndDate")
    public JAXBElement<String> createJobEndDate(String value) {
        return new JAXBElement<String>(_JobEndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AltPhone")
    public JAXBElement<String> createAltPhone(String value) {
        return new JAXBElement<String>(_AltPhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JobDesc")
    public JAXBElement<String> createJobDesc(String value) {
        return new JAXBElement<String>(_JobDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OwnerID")
    public JAXBElement<String> createOwnerID(String value) {
        return new JAXBElement<String>(_OwnerID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Price")
    public JAXBElement<String> createPrice(String value) {
        return new JAXBElement<String>(_Price_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "State")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Balance")
    public JAXBElement<String> createBalance(String value) {
        return new JAXBElement<String>(_Balance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Operator")
    public JAXBElement<String> createOperator(String value) {
        return new JAXBElement<String>(_Operator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityOnOrder")
    public JAXBElement<String> createQuantityOnOrder(String value) {
        return new JAXBElement<String>(_QuantityOnOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DoneStatus", defaultValue = "NotDoneOnly")
    public JAXBElement<String> createDoneStatus(String value) {
        return new JAXBElement<String>(_DoneStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CompanyWebSite")
    public JAXBElement<String> createCompanyWebSite(String value) {
        return new JAXBElement<String>(_CompanyWebSite_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VendorTaxIdent")
    public JAXBElement<String> createVendorTaxIdent(String value) {
        return new JAXBElement<String>(_VendorTaxIdent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsActive")
    public JAXBElement<String> createIsActive(String value) {
        return new JAXBElement<String>(_IsActive_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SuggestedDiscountDate")
    public JAXBElement<String> createSuggestedDiscountDate(String value) {
        return new JAXBElement<String>(_SuggestedDiscountDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PostalCode")
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cost")
    public JAXBElement<String> createCost(String value) {
        return new JAXBElement<String>(_Cost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthPass")
    public JAXBElement<String> createAuthPass(String value) {
        return new JAXBElement<String>(_AuthPass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FullNameWithChildren")
    public JAXBElement<String> createFullNameWithChildren(String value) {
        return new JAXBElement<String>(_FullNameWithChildren_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalesPrice")
    public JAXBElement<String> createSalesPrice(String value) {
        return new JAXBElement<String>(_SalesPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromName")
    public JAXBElement<String> createFromName(String value) {
        return new JAXBElement<String>(_FromName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SuggestedDiscountAmount")
    public JAXBElement<String> createSuggestedDiscountAmount(String value) {
        return new JAXBElement<String>(_SuggestedDiscountAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalesTaxTotal")
    public JAXBElement<String> createSalesTaxTotal(String value) {
        return new JAXBElement<String>(_SalesTaxTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MarkupRatePercent")
    public JAXBElement<String> createMarkupRatePercent(String value) {
        return new JAXBElement<String>(_MarkupRatePercent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsVendorEligibleFor1099")
    public JAXBElement<String> createIsVendorEligibleFor1099(String value) {
        return new JAXBElement<String>(_IsVendorEligibleFor1099_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Phone")
    public JAXBElement<String> createPhone(String value) {
        return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DiscountDayOfMonth")
    public JAXBElement<BigInteger> createDiscountDayOfMonth(BigInteger value) {
        return new JAXBElement<BigInteger>(_DiscountDayOfMonth_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxRate")
    public JAXBElement<String> createTaxRate(String value) {
        return new JAXBElement<String>(_TaxRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DueDate")
    public JAXBElement<String> createDueDate(String value) {
        return new JAXBElement<String>(_DueDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExternalGUID")
    public JAXBElement<String> createExternalGUID(String value) {
        return new JAXBElement<String>(_ExternalGUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeNumber")
    public JAXBElement<String> createChargeNumber(String value) {
        return new JAXBElement<String>(_ChargeNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsPending")
    public JAXBElement<String> createIsPending(String value) {
        return new JAXBElement<String>(_IsPending_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsBillable")
    public JAXBElement<String> createIsBillable(String value) {
        return new JAXBElement<String>(_IsBillable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalesTaxPercentage")
    public JAXBElement<String> createSalesTaxPercentage(String value) {
        return new JAXBElement<String>(_SalesTaxPercentage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppliedAmount")
    public JAXBElement<String> createAppliedAmount(String value) {
        return new JAXBElement<String>(_AppliedAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Quantity")
    public JAXBElement<String> createQuantity(String value) {
        return new JAXBElement<String>(_Quantity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrintAs")
    public JAXBElement<String> createPrintAs(String value) {
        return new JAXBElement<String>(_PrintAs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupportedQBXMLVersion")
    public JAXBElement<String> createSupportedQBXMLVersion(String value) {
        return new JAXBElement<String>(_SupportedQBXMLVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsDone")
    public JAXBElement<String> createIsDone(String value) {
        return new JAXBElement<String>(_IsDone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalAmount")
    public JAXBElement<String> createTotalAmount(String value) {
        return new JAXBElement<String>(_TotalAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CheckNumber")
    public JAXBElement<String> createCheckNumber(String value) {
        return new JAXBElement<String>(_CheckNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsBilled")
    public JAXBElement<String> createIsBilled(String value) {
        return new JAXBElement<String>(_IsBilled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MiddleName")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalesDesc")
    public JAXBElement<String> createSalesDesc(String value) {
        return new JAXBElement<String>(_SalesDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AccountType")
    public JAXBElement<String> createAccountType(String value) {
        return new JAXBElement<String>(_AccountType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DiscountRatePercent")
    public JAXBElement<String> createDiscountRatePercent(String value) {
        return new JAXBElement<String>(_DiscountRatePercent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmployeeType", defaultValue = "Regular")
    public JAXBElement<String> createEmployeeType(String value) {
        return new JAXBElement<String>(_EmployeeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AccountNumber")
    public JAXBElement<String> createAccountNumber(String value) {
        return new JAXBElement<String>(_AccountNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Contact")
    public JAXBElement<String> createContact(String value) {
        return new JAXBElement<String>(_Contact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SSN")
    public JAXBElement<String> createSSN(String value) {
        return new JAXBElement<String>(_SSN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sublevel")
    public JAXBElement<Integer> createSublevel(Integer value) {
        return new JAXBElement<Integer>(_Sublevel_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ListID")
    public JAXBElement<String> createListID(String value) {
        return new JAXBElement<String>(_ListID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FullName")
    public JAXBElement<String> createFullName(String value) {
        return new JAXBElement<String>(_FullName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fax")
    public JAXBElement<String> createFax(String value) {
        return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
    }

}
