//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 03:05:54 PM PKT 
//


package com.hourtimesheet.desktop;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="CustomerQueryRq" type="{}CustomerQueryRqType"/>
 *         &lt;element name="EmployeeQueryRq" type="{}EmployeeQueryRqType"/>
 *         &lt;element name="VendorQueryRq" type="{}VendorQueryRqType"/>
 *         &lt;element name="ClassQueryRq" type="{}ClassQueryRqType"/>
 *         &lt;element name="ItemServiceQueryRq" type="{}ItemServiceQueryRqType"/>
 *         &lt;element name="PayrollItemWageQueryRq" type="{}PayrollItemWageQueryRqType"/>
 *         &lt;element name="TimeTrackingAddRq" type="{}TimeTrackingAddRqType"/>
 *       &lt;/choice>
 *       &lt;attribute name="oldMessageSetID" type="{}STRTYPE" />
 *       &lt;attribute name="newMessageSetID" type="{}STRTYPE" />
 *       &lt;attribute name="onError" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{}STRTYPE">
 *             &lt;enumeration value="stopOnError"/>
 *             &lt;enumeration value="continueOnError"/>
 *             &lt;enumeration value="rollbackOnError"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerQueryRqOrEmployeeQueryRqOrVendorQueryRq"
})
@XmlRootElement(name = "QBXMLMsgsRq")
public class QBXMLMsgsRq {

    @XmlElements({
        @XmlElement(name = "CustomerQueryRq", type = CustomerQueryRqType.class),
        @XmlElement(name = "EmployeeQueryRq", type = EmployeeQueryRqType.class),
        @XmlElement(name = "VendorQueryRq", type = VendorQueryRqType.class),
        @XmlElement(name = "ClassQueryRq", type = ClassQueryRqType.class),
        @XmlElement(name = "ItemServiceQueryRq", type = ItemServiceQueryRqType.class),
        @XmlElement(name = "PayrollItemWageQueryRq", type = PayrollItemWageQueryRqType.class),
        @XmlElement(name = "TimeTrackingAddRq", type = TimeTrackingAddRqType.class)
    })
    protected List<Object> customerQueryRqOrEmployeeQueryRqOrVendorQueryRq;
    @XmlAttribute(name = "oldMessageSetID")
    protected String oldMessageSetID;
    @XmlAttribute(name = "newMessageSetID")
    protected String newMessageSetID;
    @XmlAttribute(name = "onError", required = true)
    protected String onError;

    /**
     * Gets the value of the customerQueryRqOrEmployeeQueryRqOrVendorQueryRq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerQueryRqOrEmployeeQueryRqOrVendorQueryRq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerQueryRqOrEmployeeQueryRqOrVendorQueryRq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerQueryRqType }
     * {@link EmployeeQueryRqType }
     * {@link VendorQueryRqType }
     * {@link ClassQueryRqType }
     * {@link ItemServiceQueryRqType }
     * {@link PayrollItemWageQueryRqType }
     * {@link TimeTrackingAddRqType }
     * 
     * 
     */
    public List<Object> getCustomerQueryRqOrEmployeeQueryRqOrVendorQueryRq() {
        if (customerQueryRqOrEmployeeQueryRqOrVendorQueryRq == null) {
            customerQueryRqOrEmployeeQueryRqOrVendorQueryRq = new ArrayList<Object>();
        }
        return this.customerQueryRqOrEmployeeQueryRqOrVendorQueryRq;
    }

    /**
     * Gets the value of the oldMessageSetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldMessageSetID() {
        return oldMessageSetID;
    }

    /**
     * Sets the value of the oldMessageSetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldMessageSetID(String value) {
        this.oldMessageSetID = value;
    }

    /**
     * Gets the value of the newMessageSetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewMessageSetID() {
        return newMessageSetID;
    }

    /**
     * Sets the value of the newMessageSetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewMessageSetID(String value) {
        this.newMessageSetID = value;
    }

    /**
     * Gets the value of the onError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnError() {
        return onError;
    }

    /**
     * Sets the value of the onError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnError(String value) {
        this.onError = value;
    }

}
