//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 03:05:54 PM PKT 
//


package com.hourtimesheet.desktop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBXMLMsgsRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QBXMLMsgsRs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="CustomerQueryRs" type="{}CustomerQueryRsType"/>
 *         &lt;element name="EmployeeQueryRs" type="{}EmployeeQueryRs"/>
 *         &lt;element name="VendorQueryRs" type="{}VendorQueryRsType"/>
 *         &lt;element name="ClassQueryRs" type="{}ClassQueryRsType"/>
 *         &lt;element name="ItemServiceQueryRs" type="{}ItemServiceQueryRsType"/>
 *         &lt;element name="PayrollItemWageQueryRs" type="{}PayrollItemWageQueryRsType"/>
 *         &lt;element name="TimeTrackingAddRs" type="{}TimeTrackingAddRsType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBXMLMsgsRs", propOrder = {
    "customerQueryRs",
    "employeeQueryRs",
    "vendorQueryRs",
    "classQueryRs",
    "itemServiceQueryRs",
    "payrollItemWageQueryRs",
    "timeTrackingAddRs"
})
public class QBXMLMsgsRs {

    @XmlElement(name = "CustomerQueryRs")
    protected CustomerQueryRsType customerQueryRs;
    @XmlElement(name = "EmployeeQueryRs")
    protected EmployeeQueryRs employeeQueryRs;
    @XmlElement(name = "VendorQueryRs")
    protected VendorQueryRsType vendorQueryRs;
    @XmlElement(name = "ClassQueryRs")
    protected ClassQueryRsType classQueryRs;
    @XmlElement(name = "ItemServiceQueryRs")
    protected ItemServiceQueryRsType itemServiceQueryRs;
    @XmlElement(name = "PayrollItemWageQueryRs")
    protected PayrollItemWageQueryRsType payrollItemWageQueryRs;
    @XmlElement(name = "TimeTrackingAddRs")
    protected TimeTrackingAddRsType timeTrackingAddRs;

    /**
     * Gets the value of the customerQueryRs property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerQueryRsType }
     *     
     */
    public CustomerQueryRsType getCustomerQueryRs() {
        return customerQueryRs;
    }

    /**
     * Sets the value of the customerQueryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerQueryRsType }
     *     
     */
    public void setCustomerQueryRs(CustomerQueryRsType value) {
        this.customerQueryRs = value;
    }

    /**
     * Gets the value of the employeeQueryRs property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeQueryRs }
     *     
     */
    public EmployeeQueryRs getEmployeeQueryRs() {
        return employeeQueryRs;
    }

    /**
     * Sets the value of the employeeQueryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeQueryRs }
     *     
     */
    public void setEmployeeQueryRs(EmployeeQueryRs value) {
        this.employeeQueryRs = value;
    }

    /**
     * Gets the value of the vendorQueryRs property.
     * 
     * @return
     *     possible object is
     *     {@link VendorQueryRsType }
     *     
     */
    public VendorQueryRsType getVendorQueryRs() {
        return vendorQueryRs;
    }

    /**
     * Sets the value of the vendorQueryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorQueryRsType }
     *     
     */
    public void setVendorQueryRs(VendorQueryRsType value) {
        this.vendorQueryRs = value;
    }

    /**
     * Gets the value of the classQueryRs property.
     * 
     * @return
     *     possible object is
     *     {@link ClassQueryRsType }
     *     
     */
    public ClassQueryRsType getClassQueryRs() {
        return classQueryRs;
    }

    /**
     * Sets the value of the classQueryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassQueryRsType }
     *     
     */
    public void setClassQueryRs(ClassQueryRsType value) {
        this.classQueryRs = value;
    }

    /**
     * Gets the value of the itemServiceQueryRs property.
     * 
     * @return
     *     possible object is
     *     {@link ItemServiceQueryRsType }
     *     
     */
    public ItemServiceQueryRsType getItemServiceQueryRs() {
        return itemServiceQueryRs;
    }

    /**
     * Sets the value of the itemServiceQueryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemServiceQueryRsType }
     *     
     */
    public void setItemServiceQueryRs(ItemServiceQueryRsType value) {
        this.itemServiceQueryRs = value;
    }

    /**
     * Gets the value of the payrollItemWageQueryRs property.
     * 
     * @return
     *     possible object is
     *     {@link PayrollItemWageQueryRsType }
     *     
     */
    public PayrollItemWageQueryRsType getPayrollItemWageQueryRs() {
        return payrollItemWageQueryRs;
    }

    /**
     * Sets the value of the payrollItemWageQueryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayrollItemWageQueryRsType }
     *     
     */
    public void setPayrollItemWageQueryRs(PayrollItemWageQueryRsType value) {
        this.payrollItemWageQueryRs = value;
    }

    /**
     * Gets the value of the timeTrackingAddRs property.
     * 
     * @return
     *     possible object is
     *     {@link TimeTrackingAddRsType }
     *     
     */
    public TimeTrackingAddRsType getTimeTrackingAddRs() {
        return timeTrackingAddRs;
    }

    /**
     * Sets the value of the timeTrackingAddRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeTrackingAddRsType }
     *     
     */
    public void setTimeTrackingAddRs(TimeTrackingAddRsType value) {
        this.timeTrackingAddRs = value;
    }

}
